In [1]:
# TAREA 2 - PREPROCESAMIENTO

In [2]:
import pandas as pd

In [22]:
'''
Movies Dataset (TMDB) – Ratings, Popularity, Votes
Base de datos tomada de: https://www.kaggle.com/datasets/kajaldeore04/movies-dataset-tmdb-ratings-popularity-votes/data
This dataset contains details of 8,560 movies sourced from The Movie Database (TMDB) API, including titles, overviews, release dates, popularity scores, average ratings, and total votes. It is suitable for data analysis, recommendation systems, and NLP-based projects.

Columns:

id: Unique TMDB movie ID
title: Movie title
overview: Short description or synopsis
release_date: Date of theatrical release (YYYY-MM-DD format)
popularity: Popularity score (numeric, TMDB metric)
vote_average: Average user rating (0–10 scale)
vote_count: Number of votes received
'''

'\nMovies Dataset (TMDB) – Ratings, Popularity, Votes\nBase de datos tomada de: https://www.kaggle.com/datasets/kajaldeore04/movies-dataset-tmdb-ratings-popularity-votes/data\nThis dataset contains details of 8,560 movies sourced from The Movie Database (TMDB) API, including titles, overviews, release dates, popularity scores, average ratings, and total votes. It is suitable for data analysis, recommendation systems, and NLP-based projects.\n\nColumns:\n\nid: Unique TMDB movie ID\ntitle: Movie title\noverview: Short description or synopsis\nrelease_date: Date of theatrical release (YYYY-MM-DD format)\npopularity: Popularity score (numeric, TMDB metric)\nvote_average: Average user rating (0–10 scale)\nvote_count: Number of votes received\n'

In [7]:
df = pd.read_csv('/content/movies.csv')
df

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,9/23/1994,26.9579,8.712,28675
1,1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",3/14/1972,26.5804,8.686,21701
2,2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,12/20/1974,15.6559,8.571,13099
3,3,424,Schindler's List,The true story of how businessman Oskar Schind...,12/15/1993,12.5642,8.565,16616
4,4,389,12 Angry Men,The defense and the prosecution have rested an...,4/10/1957,14.6028,8.549,9307
...,...,...,...,...,...,...,...,...
8555,8555,238603,Earth to Echo,After a construction project begins digging in...,6/14/2014,1.6137,5.900,593
8556,8556,11968,Into the Blue,When they take some friends on an extreme spor...,9/30/2005,3.3432,5.902,1539
8557,8557,439079,The Nun,A priest with a haunted past and a novice on t...,9/5/2018,15.1733,5.901,6862
8558,8558,513409,Earthquake Bird,"Tokyo, Japan, 1989. Lucy Fly, a foreigner who ...",11/1/2019,1.1859,5.900,448
8559,8559,362637,Opposites Attract,"She's a divorce lawyer, single mother and perp...",10/8/2015,0.5438,5.900,304

In [9]:
df.head(1)

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,9/23/1994,26.9579,8.712,28675

In [10]:
df.tail(3)

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
8557,8557,439079,The Nun,A priest with a haunted past and a novice on t...,9/5/2018,15.1733,5.901,6862
8558,8558,513409,Earthquake Bird,"Tokyo, Japan, 1989. Lucy Fly, a foreigner who ...",11/1/2019,1.1859,5.900,448
8559,8559,362637,Opposites Attract,"She's a divorce lawyer, single mother and perp...",10/8/2015,0.5438,5.900,304

In [11]:
df.describe()

        Unnamed: 0            id   popularity  vote_average    vote_count
count  8560.000000  8.560000e+03  8560.000000   8560.000000   8560.000000
mean   4279.500000  2.163106e+05     4.370749      6.867912   2192.376869
std    2471.203485  2.879922e+05    21.398538      0.581178   3430.230375
min       0.000000  2.000000e+00     0.003400      5.900000    300.000000
25%    2139.750000  1.010800e+04     1.728925      6.400000    485.000000
50%    4279.500000  3.776850e+04     2.566650      6.812500    916.000000
75%    6419.250000  3.991332e+05     4.248675      7.298250   2237.000000
max    8559.000000  1.426776e+06  1274.226400      8.712000  37773.000000

In [12]:
df.shape

(8560, 8)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8560 entries, 0 to 8559
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8560 non-null   int64
 1   id            8560 non-null   int64
 2   title         8560 non-null   object
 3   overview      8559 non-null   object
 4   release_date  8558 non-null   object
 5   popularity    8560 non-null   float64
 6   vote_average  8560 non-null   float64
 7   vote_count    8560 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 535.1+ KB

In [14]:
df.dtypes

Unnamed: 0        int64
id                int64
title            object
overview         object
release_date     object
popularity      float64
vote_average    float64
vote_count        int64
dtype: object

In [15]:
df.columns

Index(['Unnamed: 0', 'id', 'title', 'overview', 'release_date', 'popularity',
       'vote_average', 'vote_count'],
      dtype='object')

In [17]:
df['title'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
8555    False
8556    False
8557    False
8558    False
8559    False
Name: title, Length: 8560, dtype: bool

In [18]:
df[['title', 'release_date', 'popularity']]

                         title release_date  popularity
0     The Shawshank Redemption    9/23/1994     26.9579
1                The Godfather    3/14/1972     26.5804
2        The Godfather Part II   12/20/1974     15.6559
3             Schindler's List   12/15/1993     12.5642
4                 12 Angry Men    4/10/1957     14.6028
...                        ...          ...         ...
8555             Earth to Echo    6/14/2014      1.6137
8556             Into the Blue    9/30/2005      3.3432
8557                   The Nun     9/5/2018     15.1733
8558           Earthquake Bird    11/1/2019      1.1859
8559         Opposites Attract    10/8/2015      0.5438

[8560 rows x 3 columns]

In [19]:
df.head()

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,9/23/1994,26.9579,8.712,28675
1,1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",3/14/1972,26.5804,8.686,21701
2,2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,12/20/1974,15.6559,8.571,13099
3,3,424,Schindler's List,The true story of how businessman Oskar Schind...,12/15/1993,12.5642,8.565,16616
4,4,389,12 Angry Men,The defense and the prosecution have rested an...,4/10/1957,14.6028,8.549,9307

In [23]:
df.rename(columns={'title' : 'movie_name'})

,Unnamed: 0,id,movie_name,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,9/23/1994,26.9579,8.712,28675
1,1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",3/14/1972,26.5804,8.686,21701
2,2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,12/20/1974,15.6559,8.571,13099
3,3,424,Schindler's List,The true story of how businessman Oskar Schind...,12/15/1993,12.5642,8.565,16616
4,4,389,12 Angry Men,The defense and the prosecution have rested an...,4/10/1957,14.6028,8.549,9307
...,...,...,...,...,...,...,...,...
8555,8555,238603,Earth to Echo,After a construction project begins digging in...,6/14/2014,1.6137,5.900,593
8556,8556,11968,Into the Blue,When they take some friends on an extreme spor...,9/30/2005,3.3432,5.902,1539
8557,8557,439079,The Nun,A priest with a haunted past and a novice on t...,9/5/2018,15.1733,5.901,6862
8558,8558,513409,Earthquake Bird,"Tokyo, Japan, 1989. Lucy Fly, a foreigner who ...",11/1/2019,1.1859,5.900,448
8559,8559,362637,Opposites Attract,"She's a divorce lawyer, single mother and perp...",10/8/2015,0.5438,5.900,304

In [24]:
df_t = df.copy()
df_t = df_t.rename(columns={'movie_name' : 'title'})

In [25]:
df_t

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,9/23/1994,26.9579,8.712,28675
1,1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",3/14/1972,26.5804,8.686,21701
2,2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,12/20/1974,15.6559,8.571,13099
3,3,424,Schindler's List,The true story of how businessman Oskar Schind...,12/15/1993,12.5642,8.565,16616
4,4,389,12 Angry Men,The defense and the prosecution have rested an...,4/10/1957,14.6028,8.549,9307
...,...,...,...,...,...,...,...,...
8555,8555,238603,Earth to Echo,After a construction project begins digging in...,6/14/2014,1.6137,5.900,593
8556,8556,11968,Into the Blue,When they take some friends on an extreme spor...,9/30/2005,3.3432,5.902,1539
8557,8557,439079,The Nun,A priest with a haunted past and a novice on t...,9/5/2018,15.1733,5.901,6862
8558,8558,513409,Earthquake Bird,"Tokyo, Japan, 1989. Lucy Fly, a foreigner who ...",11/1/2019,1.1859,5.900,448
8559,8559,362637,Opposites Attract,"She's a divorce lawyer, single mother and perp...",10/8/2015,0.5438,5.900,304